### ISSUE TITLE
add a Java example

### ISSUE THREAD

**Issue by afeld** [18F/cf-hello-worlds#15]
Maybe using [Play](https://www.playframework.com/)?

**Comment by johnscancella** [comment]
If you are not dead set on using Play, I created #21 that uses [spring-boot](http://projects.spring.io/spring-boot/)

**Comment by afeld** [comment]
* [x] add a Spring example
* [ ] add a Play example

**Comment by pburkholder** [comment]
We have one java example, which will suffice until someone submits a Play PR.
