### ISSUE TITLE
meteor example seems to be broken

### ISSUE THREAD

**Issue by timwood** [18F/cf-hello-worlds#16]
I'm getting:
```
FAILED
Domain 18f.gov not found
```

When trying to deploy the meteor hello world example provided in this repo. Looks like the domain my account is part of is "apps.cloud.gov", and changing the domain in manifest.yml to that allows me to properly deploy the example.

Should manifest.yml be updated in this example to include this domain?

**Comment by afeld** [comment]
Good catch, thanks! https://github.com/18F/cf-hello-worlds/pull/19
