### ISSUE TITLE
Make this more accessible to non-framework-nerds

### ISSUE THREAD

**Issue by mogul** [18F/cf-hello-worlds#24]
The cf-hello-worlds repository is less accessible for newbs than it could be since there’s inconsistent indication of the language in use for each of the subdirectories. The language would likely be more relevant, meaningful, and communicative than the framework names... Even as something of a polyglot, I have no idea what languages padrino, sinatra, and flask refer to. So maybe the subdirectories could be renamed in the form `$LANG[-$FRAMEWORK]`?

**Comment by afeld** [comment]
Maybe `$LANG/$FRAMEWORK/`? Then we could have a README in the language directories with any general guidance.

**Comment by jmcarp** [comment]
I'm going to put in another plug for #22 here--should we be scheduling new work on this repo when it basically duplicates another community effort?
