### ISSUE TITLE
README.md url typo

### ISSUE THREAD

**Issue by johangithub** [18F/cf-hello-worlds#31]
Hello,

It's my first time using cf. On your README.md, 
```
https://APPNAME.apps.cloud.gov/
```
didn't work but
```
https://APPNAME.app.cloud.gov/
```
worked.

**Comment by brittag** [comment]
You're right, thanks for catching that and reporting it! I put in a pull request here to update this: https://github.com/18F/cf-hello-worlds/pull/32

You're also welcome to fork these repositories and make PRs on them if you like - we welcome contributions.
