### ISSUE TITLE
python-flask fails during staging: /usr/lib/ruby/2.3.0/uri/rfc3986_parser.rb:67:in `split': bad URI(is not URI?): https://lang-python.s3.amazonaws.com//runtimes/python-2.7.13.tar.gz (URI::InvalidURIError)

### ISSUE THREAD

**Issue by jchamlin** [18F/cf-hello-worlds#36]
% cf push hello-world-python-flask --random-route

[...]
Starting app hello-world-python-flask in org trial / space I831870 as i831870...
Creating container
Successfully created container
Downloading app package...
Downloaded app package (839B)
Staging...
-------> Buildpack version 1.5.18
-----> Installing python-2.7.13
/usr/lib/ruby/2.3.0/uri/rfc3986_parser.rb:67:in `split': bad URI(is not URI?): https://lang-python.s3.amazonaws.com//runtimes/python-2.7.13.tar.gz (URI::InvalidURIError)
        from /usr/lib/ruby/2.3.0/uri/rfc3986_parser.rb:73:in `parse'
        from /usr/lib/ruby/2.3.0/uri/common.rb:227:in `parse'
        from /usr/lib/ruby/2.3.0/uri/common.rb:714:in `URI'
        from /tmp/buildpack/compile-extensions/lib/uri_translator.rb:30:in `filter_uri'
        from /tmp/buildpack/compile-extensions/lib/uri_translator.rb:15:in `translate'
        from /tmp/buildpack/compile-extensions/bin/download_dependency:15:in `<main>'
DEPENDENCY MISSING IN MANIFEST:
Unfortunately, we are either unable to resolve the dependency into
a binary and version number or the requested version or version range is not supported.
Please replace the URL with a valid link or the requested version/range
with a supported version or version range.
Failed to compile droplet
Exit status 223
Staging failed: Exited with status 223
Destroying container
Successfully destroyed container

FAILED
Error restarting application: BuildpackCompileFailed

I looked here: http://lang-python.s3.amazonaws.com/ and it appears that at staging it is trying to download the python-2.7.13 runtime which does not exist at the URL. According to what I see on Amazon AWS it wants either "cedar-14" or "heroku-16" in the URL, but as you can see that section of the URL is blank (there are two slashes in a row // on the URL where cedar-14 or heroku-16 should be). Maybe a buildpack problem? Is there more information that is needed in the manifest.mf or other properties file to give the buildpack the information it needs to generate the URL to the runtime?

**Comment by brittag** [comment]
Thanks @jchamlin, this is very interesting since I've recently seen a couple other people reporting this error. I can't reproduce it myself though - when I try pushing this sample app, it builds fine. I'm asking about this in the #buildpacks channel of the [Cloud Foundry Slack](https://slack.cloudfoundry.org/) since I also wonder if it could be a buildpack problem.

What Cloud Foundry deployment are you working with? (Based on your org and space name, it doesn't sound like cloud.gov.)

**Comment by jchamlin** [comment]
I'm working with SAP Cloud Platform (SCP). The most recent change of the manifest.yml which changed from using the buildpack with the full URL to just the buildpack name seems to have fixed the problem. I bet our environment has an older buildpack, and doesn't work with the latest at the URL.
